version: '3.8'

services:
  creator-tools:
    image: ghcr.io/minhung1126/creator-tools:latest
    container_name: youtube_creator_tools
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - HOST=${HOST:-http://localhost:8000}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SECRET_KEY=${SECRET_KEY:-creator-tools-super-secret-key-2026}
    restart: unless-stopped
