services:
  creator-tools:
    image: ghcr.io/minhung1126/creator-tools:latest
    container_name: creator_tools
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
